//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TReport.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnergyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnergyResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TReport.App_LocalResources.EnergyResource", typeof(EnergyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средне давление.
        /// </summary>
        public static string avg_pressure {
            get {
                return ResourceManager.GetString("avg_pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя температура.
        /// </summary>
        public static string avg_temp {
            get {
                return ResourceManager.GetString("avg_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дутье.
        /// </summary>
        public static string blast {
            get {
                return ResourceManager.GetString("blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доменный газ.
        /// </summary>
        public static string blast_furnace_gas {
            get {
                return ResourceManager.GetString("blast_furnace_gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доменный газ (на БВН).
        /// </summary>
        public static string blast_furnace_gas_bvn {
            get {
                return ResourceManager.GetString("blast_furnace_gas_bvn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход доменного газа на ГСУ №5.
        /// </summary>
        public static string blast_furnace_gas_gsu5 {
            get {
                return ResourceManager.GetString("blast_furnace_gas_gsu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сжатый воздух.
        /// </summary>
        public static string compressed_air {
            get {
                return ResourceManager.GetString("compressed_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расход за сутки.
        /// </summary>
        public static string flow_sutky {
            get {
                return ResourceManager.GetString("flow_sutky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Природный газ.
        /// </summary>
        public static string natur_gas {
            get {
                return ResourceManager.GetString("natur_gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Природный газ на печь.
        /// </summary>
        public static string natur_gas_bf {
            get {
                return ResourceManager.GetString("natur_gas_bf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Природный газ на ТЭЦ-3.
        /// </summary>
        public static string natur_gas_hpp3 {
            get {
                return ResourceManager.GetString("natur_gas_hpp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Природный газ на технужды.
        /// </summary>
        public static string natur_gas_tn {
            get {
                return ResourceManager.GetString("natur_gas_tn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Азот.
        /// </summary>
        public static string nitrogen {
            get {
                return ResourceManager.GetString("nitrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кислород.
        /// </summary>
        public static string oxygen {
            get {
                return ResourceManager.GetString("oxygen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планиметрическое число.
        /// </summary>
        public static string planimetric_value {
            get {
                return ResourceManager.GetString("planimetric_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приведенный расход за сутки.
        /// </summary>
        public static string pr_flow_sutky {
            get {
                return ResourceManager.GetString("pr_flow_sutky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пар.
        /// </summary>
        public static string steam {
            get {
                return ResourceManager.GetString("steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время подачи, макс.
        /// </summary>
        public static string time_max {
            get {
                return ResourceManager.GetString("time_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время подачи, норма.
        /// </summary>
        public static string time_norm {
            get {
                return ResourceManager.GetString("time_norm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Колошниковый газ (на выходе).
        /// </summary>
        public static string top_gas {
            get {
                return ResourceManager.GetString("top_gas", resourceCulture);
            }
        }
    }
}
